site_name: Performance Portability
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
theme: 'material'
pages:
- Introduction: index.md
- Office of Science Facilities:
    - Overview: facilities/overview.md
    - Tools: facilities/tools.md
    - Comparison: facilities/comparison.md
    - Resources: facilities/resources.md
- Performance Portability:
    - Definition: perfport/definition.md
    - Measurements: perfport/measurements.md
    - Approaches:
        - Libraries: perfport/libraries/index.md
        - Directives: perfport/directives/index.md
        - Frameworks: perfport/frameworks/index.md
        - DSL: perfport/dsl/index.md
        - Models: perfport/models/index.md
    - Case Studies:
        - amr: case_studies/amr/index.md
- Demo: demo/demo.md
